package com.zhiqi.campusassistant.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhiqi.campusassistant.common.entity.CacheData;
import com.zhiqi.campusassistant.core.login.entity.LoginUser;

import com.zhiqi.campusassistant.dao.CacheDataDao;
import com.zhiqi.campusassistant.dao.LoginUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cacheDataDaoConfig;
    private final DaoConfig loginUserDaoConfig;

    private final CacheDataDao cacheDataDao;
    private final LoginUserDao loginUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cacheDataDaoConfig = daoConfigMap.get(CacheDataDao.class).clone();
        cacheDataDaoConfig.initIdentityScope(type);

        loginUserDaoConfig = daoConfigMap.get(LoginUserDao.class).clone();
        loginUserDaoConfig.initIdentityScope(type);

        cacheDataDao = new CacheDataDao(cacheDataDaoConfig, this);
        loginUserDao = new LoginUserDao(loginUserDaoConfig, this);

        registerDao(CacheData.class, cacheDataDao);
        registerDao(LoginUser.class, loginUserDao);
    }
    
    public void clear() {
        cacheDataDaoConfig.clearIdentityScope();
        loginUserDaoConfig.clearIdentityScope();
    }

    public CacheDataDao getCacheDataDao() {
        return cacheDataDao;
    }

    public LoginUserDao getLoginUserDao() {
        return loginUserDao;
    }

}
